#!/bin/bash

[ $# -eq 1 -a -f "$1" ] || { echo 'Usage: compile <cminor file>'; exit 1; }
make && {
	FIN=$1
	OUT=$(java cminor.Compiler -o - "$FIN") && {
		echo "==== $FIN ===="
		cat "$FIN"
		echo "==== x86 Code ===="
		echo "$OUT"
	}
}
exit $?

