#!/bin/bash

if [ $# -ne 1 ]; then
	echo 'Usage: resolve <cminor file>'
	exit 1
fi

make >& /dev/null || exit 1
CFFILE=$1
DOTCODE=$(java cminor.Compiler -s -o - "$CFFILE")
RC=$?
echo "==== File $CFFILE ===="
cat "$CFFILE"
echo "==== ===="
if [ $RC -eq 0 ]; then
	IMG=$(tempfile -s .png)
	echo "$DOTCODE" | dot -Tpng > "$IMG"
	gnome-open "$IMG" >& /dev/null
fi

