#!/bin/bash

[ $# -eq 1 -a -f "$1" ] || { echo 'Usage: resolve <cminor file>'; exit 1; }
make && {
	FIN=$1
	OUT=$(java cminor.Compiler -s -o - "$FIN") && {
		echo "==== $FIN ===="
		cat "$FIN"
		echo "==== Displaying AST with resolved symbols... ===="
		IMG=$(tempfile -s .png)
		echo "$OUT" | dot -Tpng -o "$IMG"
		xdg-open "$IMG"
	}
}
exit $?

