#!/bin/bash

[ $# -eq 1 -a -f "$1" ] || { echo 'Usage: typecheck <cminor file>'; exit 1; }
make && {
	FIN=$1
	echo "==== $FIN ===="
	cat "$FIN"
	echo "==== Result ===="
	java cminor.Compiler -l "$FIN" && {
		echo "Success"
	} || {
		echo "Failure"
	}
}
exit $?

